function evaluate_sonicom_validation_reconstruction(subjectLimit, outputName, publishResults, v3PredictionName, v31PredictionName)
%EVALUATE_SONICOM_VALIDATION_RECONSTRUCTION Strict validation metrics.
%
% The function reads only the locked SONICOM validation split. It combines
% predicted residual magnitudes with the original MCA phase stored in the
% residual HDF5 files, reconstructs HRIRs, and compares MCA, MLP v1 and MLP
% v2 with AKerbError, contralateral high-frequency error and HRIR-energy ILD.
% Pass a v3 reconstruction run name as the fourth argument to include the
% locked MLP+CNN v3 in the same evaluation and figures. Pass a v3.1 run as
% the fifth argument to compare MCA, both MLPs, v3 and v3.1 together.

if nargin < 1 || isempty(subjectLimit)
    subjectLimit = inf;
end
if nargin < 2 || isempty(outputName)
    outputName = 'sonicom_mlp_q26_v2_strict_validation';
end
if nargin < 3 || isempty(publishResults)
    publishResults = true;
end
if nargin < 4
    v3PredictionName = '';
end
if nargin < 5
    v31PredictionName = '';
end
validateattributes(subjectLimit, {'numeric'}, {'scalar', 'positive'});
validateattributes(outputName, {'char', 'string'}, {'scalartext'});
validateattributes(publishResults, {'logical', 'numeric'}, {'scalar'});
validateattributes(v3PredictionName, {'char', 'string'}, {'scalartext'});
validateattributes(v31PredictionName, {'char', 'string'}, {'scalartext'});
outputName = char(outputName);
publishResults = logical(publishResults);
v3PredictionName = char(v3PredictionName);
v31PredictionName = char(v31PredictionName);
includeV3 = ~isempty(v3PredictionName);
includeV31 = ~isempty(v31PredictionName);
assert(~includeV31 || includeV3, ...
    'A v3.1 comparison requires the v3 prediction run as argument four.');

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
supdeqDir = fullfile(projectRoot, 'external', 'SUpDEq');
datasetRoot = fullfile(projectRoot, 'data', 'processed', ...
    'sonicom_residual_q26_v1');
sofaRoot = fullfile(projectRoot, 'data', 'HRTF', ...
    'sonicom_measured_ffcmp_minphase_44k1', 'subjects');
splitFile = fullfile(projectRoot, 'configs', 'data', ...
    'sonicom_subject_split_v1.csv');
v1PredictionRoot = fullfile(projectRoot, 'artifacts', ...
    'reconstruction', 'sonicom_q26_validation_v1');
v2PredictionRoot = fullfile(projectRoot, 'artifacts', ...
    'reconstruction', 'sonicom_q26_validation_v2');
if includeV3
    v3PredictionRoot = fullfile(projectRoot, 'artifacts', ...
        'reconstruction', v3PredictionName);
else
    v3PredictionRoot = '';
end
if includeV31
    v31PredictionRoot = fullfile(projectRoot, 'artifacts', ...
        'reconstruction', v31PredictionName);
else
    v31PredictionRoot = '';
end
if publishResults
    outputRoot = fullfile(projectRoot, 'results', outputName);
else
    outputRoot = fullfile(projectRoot, 'artifacts', 'evaluation', outputName);
end
figuresRoot = fullfile(outputRoot, 'figures');

assert(isfolder(supdeqDir), 'SUpDEq directory not found: %s', supdeqDir);
assert(isfolder(datasetRoot), 'Dataset root not found: %s', datasetRoot);
assert(isfolder(sofaRoot), 'SOFA root not found: %s', sofaRoot);
assert(isfile(splitFile), 'Split file not found: %s', splitFile);
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

originalDir = pwd;
restoreDirectory = onCleanup(@() cd(originalDir));
cd(supdeqDir);
supdeq_start;
cd(projectRoot);

splitTable = readtable(splitFile, 'TextType', 'string');
validationRows = splitTable(splitTable.split == "val", :);
assert(height(validationRows) == 44, ...
    'Expected exactly 44 locked validation subjects.');
subjectCount = min(height(validationRows), floor(subjectLimit));
validationRows = validationRows(1:subjectCount, :);

configuration = struct( ...
    'schemaVersion', '1.0', ...
    'createdOn', char(datetime('now', 'TimeZone', 'local')), ...
    'split', 'val', ...
    'testSubjectCountRead', 0, ...
    'subjectCount', subjectCount, ...
    'datasetRoot', datasetRoot, ...
    'v1PredictionRoot', v1PredictionRoot, ...
    'v2PredictionRoot', v2PredictionRoot, ...
    'v3PredictionRoot', v3PredictionRoot, ...
    'v31PredictionRoot', v31PredictionRoot, ...
    'erbFunction', 'AKerbError', ...
    'erbFrequencyRangeHz', [50, 22050], ...
    'contralateralRegionRadiusDegrees', 25, ...
    'contralateralHighFrequencyRangeHz', [10000, 20000], ...
    'ildRegion', 'horizontal-plane interpolation directions', ...
    'reconstruction', ...
        'predicted magnitude with original MCA phase and MCA outside bins');

metricNames = ["FullSphereERB"; "Contralateral25ERB"; ...
    "ContralateralHighFrequency"; "HorizontalILDMAE"];
methodNames = ["MCA", "MLPv1", "MLPv2"];
if includeV3
    methodNames(end + 1) = "MLPCNNv3";
end
if includeV31
    methodNames(end + 1) = "MLPCNNv31";
end
methodCount = numel(methodNames);
perSubject = table();
metricLong = table();
qualityRows = table();
overview = repmat(struct( ...
    'subjectLabel', "", 'frequencyHz', [], 'referenceDb', [], ...
    'mcaDb', [], 'v1Db', [], 'v2Db', [], 'azimuthDeg', NaN, ...
    'v3Db', [], 'v31Db', [], 'elevationDeg', NaN), subjectCount, 1);

for subjectIndex = 1:subjectCount
    subjectLabel = validationRows.subject_id(subjectIndex);
    subjectNumber = sscanf(char(subjectLabel), 'P%d');
    sourceFile = fullfile(datasetRoot, 'subjects', char(subjectLabel), 'q26.h5');
    v1PredictionFile = fullfile(v1PredictionRoot, 'subjects', ...
        char(subjectLabel), 'prediction.h5');
    v2PredictionFile = fullfile(v2PredictionRoot, 'subjects', ...
        char(subjectLabel), 'prediction.h5');
    if includeV3
        v3PredictionFile = fullfile(v3PredictionRoot, 'subjects', ...
            char(subjectLabel), 'prediction.h5');
    else
        v3PredictionFile = '';
    end
    if includeV31
        v31PredictionFile = fullfile(v31PredictionRoot, 'subjects', ...
            char(subjectLabel), 'prediction.h5');
    else
        v31PredictionFile = '';
    end
    sofaFile = fullfile(sofaRoot, sprintf( ...
        '%s_FreeFieldCompMinPhase_44kHz.sofa', subjectLabel));
    assert(isfile(sourceFile), 'Missing source HDF5: %s', sourceFile);
    assert(isfile(v1PredictionFile), 'Missing v1 prediction: %s', v1PredictionFile);
    assert(isfile(v2PredictionFile), 'Missing v2 prediction: %s', v2PredictionFile);
    if includeV3
        assert(isfile(v3PredictionFile), ...
            'Missing v3 prediction: %s', v3PredictionFile);
    end
    if includeV31
        assert(isfile(v31PredictionFile), ...
            'Missing v3.1 prediction: %s', v31PredictionFile);
    end
    assert(isfile(sofaFile), 'Missing validation SOFA: %s', sofaFile);
    assert(string(h5readatt(sourceFile, '/', 'split')) == "val", ...
        'Refusing to read non-validation HDF5: %s', sourceFile);
    assert(string(h5readatt(v1PredictionFile, '/', 'split')) == "val" && ...
        string(h5readatt(v2PredictionFile, '/', 'split')) == "val", ...
        'Prediction split is not validation for %s.', subjectLabel);
    if includeV3
        assert(string(h5readatt(v3PredictionFile, '/', 'split')) == "val", ...
            'v3 prediction split is not validation for %s.', subjectLabel);
    end
    if includeV31
        assert(string(h5readatt(v31PredictionFile, '/', 'split')) == "val", ...
            'v3.1 prediction split is not validation for %s.', subjectLabel);
    end

    mcaDb = double(h5read(sourceFile, '/mca_logmag_db'));
    referenceDb = double(h5read(sourceFile, '/reference_logmag_db'));
    directionFeatures = double(h5read(sourceFile, '/direction_features'));
    frequencyHz = double(h5read(sourceFile, '/frequency_hz'));
    frequencyHz = frequencyHz(:);
    interpolationMask = logical(h5read( ...
        sourceFile, '/interpolation_evaluation_mask'));
    interpolationMask = interpolationMask(:);
    selectedPhase = double(h5read( ...
        sourceFile, '/strict_ild/mca_selected_phase_rad'));
    outsideReal = double(h5read( ...
        sourceFile, '/strict_ild/mca_outside_real'));
    outsideImag = double(h5read( ...
        sourceFile, '/strict_ild/mca_outside_imag'));
    selectedIndices = double(h5read(sourceFile, ...
        '/strict_ild/selected_bin_indices_zero_based')) + 1;
    selectedIndices = selectedIndices(:);
    outsideIndices = double(h5read(sourceFile, ...
        '/strict_ild/outside_bin_indices_zero_based')) + 1;
    outsideIndices = outsideIndices(:);
    referenceIldMetadata = double(h5read( ...
        sourceFile, '/strict_ild/reference_ild_db'));
    referenceIldMetadata = referenceIldMetadata(:);
    hrirLength = double(h5readatt(sourceFile, '/strict_ild', 'hrir_length'));
    samplingRateHz = double(h5readatt(sourceFile, '/', 'sampling_rate_hz'));
    v1ResidualDb = double(h5read(v1PredictionFile, ...
        '/predicted_residual_db'));
    v2ResidualDb = double(h5read(v2PredictionFile, ...
        '/predicted_residual_db'));
    if includeV3
        v3ResidualDb = double(h5read(v3PredictionFile, ...
            '/predicted_residual_db'));
    else
        v3ResidualDb = [];
    end
    if includeV31
        v31ResidualDb = double(h5read(v31PredictionFile, ...
            '/predicted_residual_db'));
    else
        v31ResidualDb = [];
    end

    expectedShape = [numel(frequencyHz), size(directionFeatures, 2), 2];
    assert(isequal(size(mcaDb), expectedShape), ...
        'Unexpected source tensor shape for %s.', subjectLabel);
    assert(isequal(size(v1ResidualDb), expectedShape) && ...
        isequal(size(v2ResidualDb), expectedShape), ...
        'Unexpected prediction shape for %s.', subjectLabel);
    if includeV3
        assert(isequal(size(v3ResidualDb), expectedShape), ...
            'Unexpected v3 prediction shape for %s.', subjectLabel);
    end
    if includeV31
        assert(isequal(size(v31ResidualDb), expectedShape), ...
            'Unexpected v3.1 prediction shape for %s.', subjectLabel);
    end
    assert(sum(interpolationMask) == 767, ...
        'Expected 767 interpolation directions for %s.', subjectLabel);

    sofa = SOFAload(sofaFile);
    assert(isequal(size(sofa.Data.IR), [793, 2, hrirLength]), ...
        'Unexpected SOFA HRIR shape for %s.', subjectLabel);
    assert(abs(double(sofa.Data.SamplingRate) - samplingRateHz) < 1e-9, ...
        'Sampling-rate mismatch for %s.', subjectLabel);
    sofaAzimuth = mod(double(sofa.SourcePosition(:, 1)), 360);
    sofaElevation = double(sofa.SourcePosition(:, 2));
    azimuthError = abs(mod(sofaAzimuth - directionFeatures(1, :).' + ...
        180, 360) - 180);
    elevationError = abs(sofaElevation - directionFeatures(2, :).');
    assert(max(azimuthError) <= 1e-7 && max(elevationError) <= 1e-7, ...
        'SOFA/HDF5 direction ordering mismatch for %s.', subjectLabel);
    referenceHrirLeft = squeeze(double(sofa.Data.IR(:, 1, :))).';
    referenceHrirRight = squeeze(double(sofa.Data.IR(:, 2, :))).';

    residuals = {zeros(expectedShape), v1ResidualDb, v2ResidualDb};
    if includeV3
        residuals{end + 1} = v3ResidualDb;
    end
    if includeV31
        residuals{end + 1} = v31ResidualDb;
    end
    hrirLeft = cell(1, methodCount);
    hrirRight = cell(1, methodCount);
    selectedMagnitudeDb = cell(1, methodCount);
    for methodIndex = 1:methodCount
        selectedMagnitudeDb{methodIndex} = mcaDb + residuals{methodIndex};
        hrirLeft{methodIndex} = reconstruct_hrir( ...
            selectedMagnitudeDb{methodIndex}(:, :, 1), ...
            selectedPhase(:, :, 1), outsideReal(:, :, 1), ...
            outsideImag(:, :, 1), selectedIndices, outsideIndices, ...
            hrirLength);
        hrirRight{methodIndex} = reconstruct_hrir( ...
            selectedMagnitudeDb{methodIndex}(:, :, 2), ...
            selectedPhase(:, :, 2), outsideReal(:, :, 2), ...
            outsideImag(:, :, 2), selectedIndices, outsideIndices, ...
            hrirLength);
    end

    referenceIldRaw = calculate_ild(referenceHrirLeft, referenceHrirRight);
    referenceIldError = max(abs(referenceIldRaw - referenceIldMetadata));
    assert(referenceIldError <= 2e-4, ...
        'Reference ILD metadata mismatch %.6g dB for %s.', ...
        referenceIldError, subjectLabel);

    azimuthDeg = directionFeatures(1, :).';
    elevationDeg = directionFeatures(2, :).';
    y = directionFeatures(4, :).';
    solidAngleWeight = directionFeatures(6, :).';
    fullMask = interpolationMask;
    leftContra25Mask = interpolationMask & great_circle_mask( ...
        azimuthDeg, elevationDeg, 270, 0, 25);
    rightContra25Mask = interpolationMask & great_circle_mask( ...
        azimuthDeg, elevationDeg, 90, 0, 25);
    leftContraHemisphereMask = interpolationMask & y < -1e-12;
    rightContraHemisphereMask = interpolationMask & y > 1e-12;
    horizontalMask = interpolationMask & abs(elevationDeg) <= 1e-9;
    assert(any(leftContra25Mask) && any(rightContra25Mask), ...
        'Contralateral 25-degree region is empty.');
    assert(any(horizontalMask), 'Horizontal validation mask is empty.');

    metricValues = zeros(methodCount, 4);
    erbErrorsLeft = cell(1, methodCount);
    erbErrorsRight = cell(1, methodCount);
    for methodIndex = 1:methodCount
        [erbErrorsLeft{methodIndex}, erbFrequencyHz] = AKerbError( ...
            hrirLeft{methodIndex}(:, fullMask), ...
            referenceHrirLeft(:, fullMask), ...
            [50, samplingRateHz / 2], samplingRateHz);
        erbErrorsRight{methodIndex} = AKerbError( ...
            hrirRight{methodIndex}(:, fullMask), ...
            referenceHrirRight(:, fullMask), ...
            [50, samplingRateHz / 2], samplingRateHz);
        fullWeights = normalized_weights(solidAngleWeight(fullMask));
        metricValues(methodIndex, 1) = 0.5 * (...
            mean(abs(erbErrorsLeft{methodIndex}) * fullWeights) + ...
            mean(abs(erbErrorsRight{methodIndex}) * fullWeights));

        leftWithinFull = leftContra25Mask(fullMask);
        rightWithinFull = rightContra25Mask(fullMask);
        leftWeights = normalized_weights( ...
            solidAngleWeight(leftContra25Mask));
        rightWeights = normalized_weights( ...
            solidAngleWeight(rightContra25Mask));
        metricValues(methodIndex, 2) = 0.5 * (...
            mean(abs(erbErrorsLeft{methodIndex}(:, leftWithinFull)) * ...
                leftWeights) + ...
            mean(abs(erbErrorsRight{methodIndex}(:, rightWithinFull)) * ...
                rightWeights));

        metricValues(methodIndex, 3) = 0.5 * (...
            high_frequency_error( ...
                selectedMagnitudeDb{methodIndex}(:, :, 1), ...
                referenceDb(:, :, 1), frequencyHz, ...
                leftContraHemisphereMask, solidAngleWeight) + ...
            high_frequency_error( ...
                selectedMagnitudeDb{methodIndex}(:, :, 2), ...
                referenceDb(:, :, 2), frequencyHz, ...
                rightContraHemisphereMask, solidAngleWeight));

        methodIld = calculate_ild( ...
            hrirLeft{methodIndex}, hrirRight{methodIndex});
        metricValues(methodIndex, 4) = mean(abs( ...
            methodIld(horizontalMask) - referenceIldMetadata(horizontalMask)));
    end

    row = table(subjectLabel, subjectNumber, ...
        metricValues(1, 1), metricValues(2, 1), metricValues(3, 1), ...
        metricValues(1, 2), metricValues(2, 2), metricValues(3, 2), ...
        metricValues(1, 3), metricValues(2, 3), metricValues(3, 3), ...
        metricValues(1, 4), metricValues(2, 4), metricValues(3, 4), ...
        'VariableNames', {'SubjectLabel', 'SubjectID', ...
        'MCAFullSphereERB_dB', 'MLPv1FullSphereERB_dB', ...
        'MLPv2FullSphereERB_dB', ...
        'MCAContralateral25ERB_dB', 'MLPv1Contralateral25ERB_dB', ...
        'MLPv2Contralateral25ERB_dB', ...
        'MCAContralateralHighFrequency_dB', ...
        'MLPv1ContralateralHighFrequency_dB', ...
        'MLPv2ContralateralHighFrequency_dB', ...
        'MCAHorizontalILDMAE_dB', 'MLPv1HorizontalILDMAE_dB', ...
        'MLPv2HorizontalILDMAE_dB'});
    if includeV3
        row = addvars(row, ...
            metricValues(4, 1), metricValues(4, 2), ...
            metricValues(4, 3), metricValues(4, 4), ...
            'NewVariableNames', {'MLPCNNv3FullSphereERB_dB', ...
            'MLPCNNv3Contralateral25ERB_dB', ...
            'MLPCNNv3ContralateralHighFrequency_dB', ...
            'MLPCNNv3HorizontalILDMAE_dB'});
    end
    if includeV31
        row = addvars(row, ...
            metricValues(5, 1), metricValues(5, 2), ...
            metricValues(5, 3), metricValues(5, 4), ...
            'NewVariableNames', {'MLPCNNv31FullSphereERB_dB', ...
            'MLPCNNv31Contralateral25ERB_dB', ...
            'MLPCNNv31ContralateralHighFrequency_dB', ...
            'MLPCNNv31HorizontalILDMAE_dB'});
    end
    perSubject = [perSubject; row]; %#ok<AGROW>
    for methodIndex = 1:methodCount
        for metricIndex = 1:4
            metricLong = [metricLong; table(subjectLabel, subjectNumber, ...
                methodNames(methodIndex), metricNames(metricIndex), ...
                metricValues(methodIndex, metricIndex), ...
                'VariableNames', {'SubjectLabel', 'SubjectID', ...
                'Method', 'Metric', 'Value_dB'})]; %#ok<AGROW>
        end
    end
    qualityRows = [qualityRows; table(subjectLabel, subjectNumber, ...
        referenceIldError, sum(fullMask), sum(horizontalMask), ...
        numel(erbFrequencyHz), ...
        'VariableNames', {'SubjectLabel', 'SubjectID', ...
        'ReferenceILDMetadataMaxError_dB', ...
        'InterpolationDirectionCount', 'HorizontalDirectionCount', ...
        'ERBBandCount'})]; %#ok<AGROW>

    [~, overviewIndex] = min(great_circle_distance( ...
        azimuthDeg, elevationDeg, 270, 0) + 1e6 * ~interpolationMask);
    plotMask = frequencyHz >= 100 & frequencyHz <= 20000;
    overview(subjectIndex).subjectLabel = subjectLabel;
    overview(subjectIndex).frequencyHz = frequencyHz(plotMask);
    overview(subjectIndex).referenceDb = ...
        referenceDb(plotMask, overviewIndex, 1);
    overview(subjectIndex).mcaDb = mcaDb(plotMask, overviewIndex, 1);
    overview(subjectIndex).v1Db = ...
        selectedMagnitudeDb{2}(plotMask, overviewIndex, 1);
    overview(subjectIndex).v2Db = ...
        selectedMagnitudeDb{3}(plotMask, overviewIndex, 1);
    if includeV3
        overview(subjectIndex).v3Db = ...
            selectedMagnitudeDb{4}(plotMask, overviewIndex, 1);
    end
    if includeV31
        overview(subjectIndex).v31Db = ...
            selectedMagnitudeDb{5}(plotMask, overviewIndex, 1);
    end
    overview(subjectIndex).azimuthDeg = azimuthDeg(overviewIndex);
    overview(subjectIndex).elevationDeg = elevationDeg(overviewIndex);

    fprintf('Strict SONICOM validation [%d/%d]: %s\n', ...
        subjectIndex, subjectCount, subjectLabel);
end

aggregate = make_aggregate(perSubject, metricNames, includeV3, includeV31);
writetable(perSubject, fullfile(outputRoot, 'per_subject_metrics.csv'));
writetable(metricLong, fullfile(outputRoot, 'metric_long.csv'));
writetable(qualityRows, fullfile(outputRoot, 'quality_checks.csv'));
writetable(aggregate, fullfile(outputRoot, 'aggregate_metrics.csv'));
plot_metric_overview(perSubject, figuresRoot, includeV3, includeV31);
plot_aggregate_metrics(aggregate, figuresRoot, includeV3, includeV31);
plot_hrtf_overview(overview, figuresRoot, includeV3, includeV31);

summary = struct( ...
    'schema_version', '1.0', ...
    'status', 'completed', ...
    'split', 'val', ...
    'test_subject_count_read', 0, ...
    'subject_count', subjectCount, ...
    'metric_count', height(aggregate), ...
    'aggregate', table2struct(aggregate), ...
    'configuration', configuration);
write_json(fullfile(outputRoot, 'summary.json'), summary);
fprintf('SONICOM strict validation complete: %s\n', outputRoot);
disp(aggregate);
clear restoreDirectory;
end

function hrir = reconstruct_hrir(selectedMagnitudeDb, selectedPhase, ...
        outsideReal, outsideImag, selectedIndices, outsideIndices, hrirLength)
directionCount = size(selectedMagnitudeDb, 2);
singleSidedCount = numel(selectedIndices) + numel(outsideIndices);
spectrum = complex(zeros(singleSidedCount, directionCount));
spectrum(selectedIndices, :) = 10 .^ (selectedMagnitudeDb / 20) .* ...
    exp(1i * selectedPhase);
spectrum(outsideIndices, :) = outsideReal + 1i * outsideImag;
hrirOversized = real(ifft(AKsingle2bothSidedSpectrum(spectrum)));
assert(size(hrirOversized, 1) >= hrirLength, ...
    'Reconstructed HRIR is shorter than expected.');
hrir = hrirOversized(1:hrirLength, :);
end

function ild = calculate_ild(leftHrir, rightHrir)
leftEnergy = sum(abs(leftHrir) .^ 2, 1);
rightEnergy = sum(abs(rightHrir) .^ 2, 1);
ild = (10 * log10(leftEnergy ./ rightEnergy)).';
end

function mask = great_circle_mask(azimuth, elevation, ...
        centerAzimuth, centerElevation, radiusDegrees)
mask = great_circle_distance(azimuth, elevation, ...
    centerAzimuth, centerElevation) <= radiusDegrees + 1e-10;
end

function distance = great_circle_distance(azimuth, elevation, ...
        centerAzimuth, centerElevation)
dotProduct = sind(elevation) .* sind(centerElevation) + ...
    cosd(elevation) .* cosd(centerElevation) .* ...
    cosd(azimuth - centerAzimuth);
distance = acosd(min(1, max(-1, dotProduct)));
end

function weights = normalized_weights(weights)
weights = weights(:);
assert(all(isfinite(weights)) && all(weights > 0), ...
    'Direction weights must be finite and positive.');
weights = weights / sum(weights);
end

function value = high_frequency_error(estimateDb, referenceDb, ...
        frequencyHz, directionMask, solidAngleWeight)
frequencyMask = frequencyHz > 10000 & frequencyHz <= 20000;
weights = normalized_weights(solidAngleWeight(directionMask));
errorDb = abs(estimateDb(frequencyMask, directionMask) - ...
    referenceDb(frequencyMask, directionMask));
value = mean(errorDb * weights);
end

function aggregate = make_aggregate(perSubject, metricNames, includeV3, includeV31)
baselineVariables = ["MCAFullSphereERB_dB"; ...
    "MCAContralateral25ERB_dB"; ...
    "MCAContralateralHighFrequency_dB"; ...
    "MCAHorizontalILDMAE_dB"];
v1Variables = ["MLPv1FullSphereERB_dB"; ...
    "MLPv1Contralateral25ERB_dB"; ...
    "MLPv1ContralateralHighFrequency_dB"; ...
    "MLPv1HorizontalILDMAE_dB"];
v2Variables = ["MLPv2FullSphereERB_dB"; ...
    "MLPv2Contralateral25ERB_dB"; ...
    "MLPv2ContralateralHighFrequency_dB"; ...
    "MLPv2HorizontalILDMAE_dB"];
v3Variables = ["MLPCNNv3FullSphereERB_dB"; ...
    "MLPCNNv3Contralateral25ERB_dB"; ...
    "MLPCNNv3ContralateralHighFrequency_dB"; ...
    "MLPCNNv3HorizontalILDMAE_dB"];
v31Variables = ["MLPCNNv31FullSphereERB_dB"; ...
    "MLPCNNv31Contralateral25ERB_dB"; ...
    "MLPCNNv31ContralateralHighFrequency_dB"; ...
    "MLPCNNv31HorizontalILDMAE_dB"];
aggregate = table();
for index = 1:numel(metricNames)
    mca = perSubject.(baselineVariables(index));
    v1 = perSubject.(v1Variables(index));
    v2 = perSubject.(v2Variables(index));
    row = table(metricNames(index), numel(mca), ...
        mean(mca), std(mca), mean(v1), std(v1), mean(v2), std(v2), ...
        improvement_percent(mean(mca), mean(v1)), ...
        improvement_percent(mean(mca), mean(v2)), ...
        improvement_percent(mean(v1), mean(v2)), ...
        sum(v1 < mca), sum(v2 < mca), sum(v2 < v1), ...
        'VariableNames', {'Metric', 'SubjectCount', ...
        'MCAMean_dB', 'MCAStd_dB', 'MLPv1Mean_dB', 'MLPv1Std_dB', ...
        'MLPv2Mean_dB', 'MLPv2Std_dB', ...
        'MLPv1ImprovementVsMCA_percent', ...
        'MLPv2ImprovementVsMCA_percent', ...
        'MLPv2ImprovementVsMLPv1_percent', ...
        'MLPv1ImprovedVsMCA_SubjectCount', ...
        'MLPv2ImprovedVsMCA_SubjectCount', ...
        'MLPv2ImprovedVsMLPv1_SubjectCount'});
    if includeV3
        v3 = perSubject.(v3Variables(index));
        row = addvars(row, mean(v3), std(v3), ...
            improvement_percent(mean(mca), mean(v3)), ...
            improvement_percent(mean(v2), mean(v3)), ...
            sum(v3 < mca), sum(v3 < v2), ...
            'NewVariableNames', {'MLPCNNv3Mean_dB', 'MLPCNNv3Std_dB', ...
            'MLPCNNv3ImprovementVsMCA_percent', ...
            'MLPCNNv3ImprovementVsMLPv2_percent', ...
            'MLPCNNv3ImprovedVsMCA_SubjectCount', ...
            'MLPCNNv3ImprovedVsMLPv2_SubjectCount'});
    end
    if includeV31
        v31 = perSubject.(v31Variables(index));
        row = addvars(row, mean(v31), std(v31), ...
            improvement_percent(mean(mca), mean(v31)), ...
            improvement_percent(mean(v3), mean(v31)), ...
            sum(v31 < mca), sum(v31 < v3), ...
            'NewVariableNames', {'MLPCNNv31Mean_dB', 'MLPCNNv31Std_dB', ...
            'MLPCNNv31ImprovementVsMCA_percent', ...
            'MLPCNNv31ImprovementVsMLPCNNv3_percent', ...
            'MLPCNNv31ImprovedVsMCA_SubjectCount', ...
            'MLPCNNv31ImprovedVsMLPCNNv3_SubjectCount'});
    end
    aggregate = [aggregate; row]; %#ok<AGROW>
end
end

function value = improvement_percent(baseline, estimate)
value = 100 * (baseline - estimate) / baseline;
end

function plot_metric_overview(perSubject, figuresRoot, includeV3, includeV31)
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [60, 60, 1800, 1200]);
layout = tiledlayout(figureHandle, 2, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
values = [perSubject.MCAFullSphereERB_dB, ...
    perSubject.MLPv1FullSphereERB_dB, ...
    perSubject.MLPv2FullSphereERB_dB];
if includeV3
    values(:, end + 1) = perSubject.MLPCNNv3FullSphereERB_dB;
end
if includeV31
    values(:, end + 1) = perSubject.MLPCNNv31FullSphereERB_dB;
end
plot_grouped_metric(nexttile(layout), values, ...
    'Full-sphere ERB', 'ERB error (dB)', includeV3, includeV31);
values = [perSubject.MCAContralateral25ERB_dB, ...
    perSubject.MLPv1Contralateral25ERB_dB, ...
    perSubject.MLPv2Contralateral25ERB_dB];
if includeV3
    values(:, end + 1) = perSubject.MLPCNNv3Contralateral25ERB_dB;
end
if includeV31
    values(:, end + 1) = perSubject.MLPCNNv31Contralateral25ERB_dB;
end
plot_grouped_metric(nexttile(layout), values, ...
    'Contralateral 25-degree ERB', 'ERB error (dB)', includeV3, includeV31);
values = [perSubject.MCAContralateralHighFrequency_dB, ...
    perSubject.MLPv1ContralateralHighFrequency_dB, ...
    perSubject.MLPv2ContralateralHighFrequency_dB];
if includeV3
    values(:, end + 1) = perSubject.MLPCNNv3ContralateralHighFrequency_dB;
end
if includeV31
    values(:, end + 1) = perSubject.MLPCNNv31ContralateralHighFrequency_dB;
end
plot_grouped_metric(nexttile(layout), values, ...
    'Contralateral high frequency', 'Magnitude error (dB)', includeV3, includeV31);
values = [perSubject.MCAHorizontalILDMAE_dB, ...
    perSubject.MLPv1HorizontalILDMAE_dB, ...
    perSubject.MLPv2HorizontalILDMAE_dB];
if includeV3
    values(:, end + 1) = perSubject.MLPCNNv3HorizontalILDMAE_dB;
end
if includeV31
    values(:, end + 1) = perSubject.MLPCNNv31HorizontalILDMAE_dB;
end
plot_grouped_metric(nexttile(layout), values, ...
    'Horizontal-plane strict ILD', 'ILD MAE (dB)', includeV3, includeV31);
title(layout, 'SONICOM validation: strict reconstruction metrics', ...
    'FontWeight', 'bold');
exportgraphics(figureHandle, fullfile(figuresRoot, ...
    'validation44_metric_overview.png'), 'Resolution', 180);
close(figureHandle);
end

function plot_grouped_metric(axisHandle, values, titleText, yLabelText, includeV3, includeV31)
plot(axisHandle, values(:, 1), '-', 'LineWidth', 1.0);
hold(axisHandle, 'on');
plot(axisHandle, values(:, 2), '-', 'LineWidth', 1.0);
plot(axisHandle, values(:, 3), '-', 'LineWidth', 1.2);
if includeV3
    plot(axisHandle, values(:, 4), '-', 'LineWidth', 1.4);
end
if includeV31
    plot(axisHandle, values(:, 5), '-', 'LineWidth', 1.6);
end
grid(axisHandle, 'on');
if size(values, 1) == 1
    xlim(axisHandle, [0.5, 1.5]);
else
    xlim(axisHandle, [1, size(values, 1)]);
end
xlabel(axisHandle, 'Validation subject index');
ylabel(axisHandle, yLabelText);
title(axisHandle, titleText);
labels = ["MCA", "MLP v1", "MLP v2"];
if includeV3
    labels(end + 1) = "MLP+CNN v3";
end
if includeV31
    labels(end + 1) = "MLP+CNN v3.1";
end
legend(axisHandle, labels, 'Location', 'best');
end

function plot_aggregate_metrics(aggregate, figuresRoot, includeV3, includeV31)
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100, 100, 1500, 700]);
values = [aggregate.MCAMean_dB, aggregate.MLPv1Mean_dB, ...
    aggregate.MLPv2Mean_dB];
labels = ["MCA", "MLP v1", "MLP v2"];
if includeV3
    values(:, end + 1) = aggregate.MLPCNNv3Mean_dB;
    labels(end + 1) = "MLP+CNN v3";
end
if includeV31
    values(:, end + 1) = aggregate.MLPCNNv31Mean_dB;
    labels(end + 1) = "MLP+CNN v3.1";
end
bar(values);
grid on;
xticks(1:height(aggregate));
xticklabels(["Full ERB", "Contra25 ERB", "Contra HF", "ILD"]);
ylabel('Mean error (dB)');
legend(labels, 'Location', 'best');
title('SONICOM validation aggregate strict reconstruction metrics');
exportgraphics(figureHandle, fullfile(figuresRoot, ...
    'validation44_aggregate_metrics.png'), 'Resolution', 180);
close(figureHandle);
end

function plot_hrtf_overview(overview, figuresRoot, includeV3, includeV31)
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [30, 30, 2200, 1900]);
layout = tiledlayout(figureHandle, 8, 6, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
for index = 1:numel(overview)
    axisHandle = nexttile(layout);
    semilogx(axisHandle, overview(index).frequencyHz, ...
        overview(index).referenceDb, 'k', 'LineWidth', 0.8);
    hold(axisHandle, 'on');
    semilogx(axisHandle, overview(index).frequencyHz, ...
        overview(index).mcaDb, '--', 'LineWidth', 0.7);
    semilogx(axisHandle, overview(index).frequencyHz, ...
        overview(index).v1Db, 'LineWidth', 0.7);
    semilogx(axisHandle, overview(index).frequencyHz, ...
        overview(index).v2Db, 'LineWidth', 0.9);
    if includeV3
        semilogx(axisHandle, overview(index).frequencyHz, ...
            overview(index).v3Db, 'LineWidth', 1.1);
    end
    if includeV31
        semilogx(axisHandle, overview(index).frequencyHz, ...
            overview(index).v31Db, 'LineWidth', 1.3);
    end
    grid(axisHandle, 'on');
    xlim(axisHandle, [100, 20000]);
    ylim(axisHandle, [-60, 25]);
    title(axisHandle, sprintf('%s (%.0f deg, %.0f deg)', ...
        overview(index).subjectLabel, overview(index).azimuthDeg, ...
        overview(index).elevationDeg), 'FontSize', 7);
    if index == 1
        labels = ["Reference", "MCA", "MLP v1", "MLP v2"];
        if includeV3
            labels(end + 1) = "MLP+CNN v3";
        end
        if includeV31
            labels(end + 1) = "MLP+CNN v3.1";
        end
        legend(axisHandle, labels, 'Location', 'southwest', 'FontSize', 6);
    end
end
title(layout, ['SONICOM validation: left-ear contralateral HRTF ', ...
    '(nearest pure interpolation direction)'], 'FontWeight', 'bold');
exportgraphics(figureHandle, fullfile(figuresRoot, ...
    'validation44_contralateral_hrtf_overview.png'), 'Resolution', 180);
close(figureHandle);
end

function write_json(path, value)
text = jsonencode(value, 'PrettyPrint', true);
file = fopen(path, 'w');
assert(file ~= -1, 'Could not open JSON output: %s', path);
cleanup = onCleanup(@() fclose(file));
fprintf(file, '%s\n', text);
clear cleanup;
end
