function evaluate_mlp_cnn_v3_reconstruction()
%EVALUATE_MLP_CNN_V3_RECONSTRUCTION Run strict test metrics for locked v3.

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));

outputRoot = fullfile( ...
    projectRoot, 'artifacts', 'reconstruction', 'mlp_cnn_n03_v3_cnn_only');
cacheRoot = fullfile( ...
    projectRoot, 'artifacts', 'reconstruction', 'mlp_n03_v1');

mcar.evaluate_test_reconstruction( ...
    'mlp_cnn_n03_v3_cnn_only', ...
    'mlp_n03_v1', ...
    outputRoot, ...
    cacheRoot, ...
    "MCA+ResidualMLPCNN", ...
    "MCA + residual MLP-CNN");
end
