function plot_v32_previous_scratch_fusion()
%PLOT_V32_PREVIOUS_SCRATCH_FUSION Visualize strict validation fusion gains.

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
studyRoot = fullfile(projectRoot, 'results', ...
    'sonicom_mlp_cnn_q26_v32_cnn_reinit_joint_v1');
previousRoot = fullfile(projectRoot, 'results', ...
    'sonicom_mlp_cnn_q26_v321_cnn_reinit_joint_unfreeze_e10_strict_validation');
scratchRoot = fullfile(projectRoot, 'results', ...
    'sonicom_mlp_cnn_q26_v32_scratch_joint_e60_strict_validation');
fusionRoot = fullfile(projectRoot, 'results', ...
    'sonicom_mlp_cnn_q26_v32_previous_scratch_fusion_strict_validation');
figureRoot = fullfile(studyRoot, 'figures');
if ~isfolder(figureRoot)
    mkdir(figureRoot);
end

comparison = readtable(fullfile(studyRoot, 'comparison.csv'), ...
    'TextType', 'string');
statistics = readtable(fullfile(studyRoot, ...
    'scratch_fusion_paired_statistics.csv'), 'TextType', 'string');
previous = readtable(fullfile(previousRoot, 'per_subject_metrics.csv'), ...
    'TextType', 'string');
scratch = readtable(fullfile(scratchRoot, 'per_subject_metrics.csv'), ...
    'TextType', 'string');
fusion = readtable(fullfile(fusionRoot, 'per_subject_metrics.csv'), ...
    'TextType', 'string');
assert(height(previous) == 44 && height(scratch) == 44 && height(fusion) == 44);
assert(isequal(previous.SubjectLabel, scratch.SubjectLabel) && ...
    isequal(scratch.SubjectLabel, fusion.SubjectLabel));

methodKeys = ["v321_cnn_reinit_joint_epoch8", ...
    "v32_scratch_joint_epoch60", "v35_output_fusion_previous30_scratch70"];
methodLabels = ["Previous joint", "Scratch", "MCAR v3.5"];
colors = [0.48 0.48 0.48; 0.23 0.51 0.96; 0.06 0.73 0.51];
metricTitles = ["Full-sphere ERB", "Contralateral 25° ERB", ...
    "Contralateral 10–20 kHz", "Horizontal ILD MAE"];
aggregateColumns = ["full_sphere_erb_db", "contralateral_25_erb_db", ...
    "contralateral_high_frequency_db", "horizontal_ild_mae_db"];
subjectColumns = ["MLPCNNv31FullSphereERB_dB", ...
    "MLPCNNv31Contralateral25ERB_dB", ...
    "MLPCNNv31ContralateralHighFrequency_dB", ...
    "MLPCNNv31HorizontalILDMAE_dB"];
statisticMetrics = ["full_sphere_erb", "contralateral_25_erb", ...
    "contralateral_hf", "horizontal_ild"];

aggregateFigure = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100 100 1500 1000]);
aggregateLayout = tiledlayout(aggregateFigure, 2, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
title(aggregateLayout, 'SONICOM Q26 strict validation (44 subjects)', ...
    'FontSize', 18, 'FontWeight', 'bold');
for metricIndex = 1:numel(metricTitles)
    ax = nexttile(aggregateLayout);
    values = zeros(1, numel(methodKeys));
    for methodIndex = 1:numel(methodKeys)
        row = comparison(comparison.method == methodKeys(methodIndex), :);
        assert(height(row) == 1);
        values(methodIndex) = row.(aggregateColumns(metricIndex));
    end
    bars = bar(ax, 1:3, values, 0.68);
    bars.FaceColor = 'flat';
    bars.CData = colors;
    bars.EdgeColor = 'none';
    title(ax, metricTitles(metricIndex), 'FontWeight', 'bold');
    ylabel(ax, 'Error (dB) — lower is better');
    ax.XTick = 1:3;
    ax.XTickLabel = methodLabels;
    ax.FontSize = 11;
    ax.TickDir = 'out';
    ax.GridAlpha = 0.20;
    grid(ax, 'on');
    ylim(ax, [0, max(values) * 1.23]);
    for methodIndex = 1:numel(values)
        text(ax, methodIndex, values(methodIndex) + max(values) * 0.025, ...
            sprintf('%.3f', values(methodIndex)), ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', ...
            'FontSize', 11, 'FontWeight', 'bold');
    end
    improvement = 100 * (values(2) - values(3)) / values(2);
    text(ax, 0.98, 0.94, ...
        sprintf('Fusion vs scratch: +%.2f%%', improvement), ...
        'Units', 'normalized', 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', 'FontSize', 10, ...
        'Color', [0.03 0.47 0.28]);
end
exportgraphics(aggregateFigure, fullfile(figureRoot, ...
    'previous_scratch_fusion_aggregate.png'), 'Resolution', 180);
close(aggregateFigure);

pairedFigure = figure('Visible', 'off', 'Color', 'white', ...
    'Position', [100 100 1450 1150]);
pairedLayout = tiledlayout(pairedFigure, 2, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
title(pairedLayout, { ...
    'Per-subject effect of MCAR v3.5 (30% previous + 70% scratch)', ...
    'Points below the dashed line are better after fusion'}, ...
    'FontSize', 17, 'FontWeight', 'bold');
for metricIndex = 1:numel(metricTitles)
    ax = nexttile(pairedLayout);
    scratchValues = scratch.(subjectColumns(metricIndex));
    fusionValues = fusion.(subjectColumns(metricIndex));
    improved = fusionValues < scratchValues;
    lower = min([scratchValues; fusionValues]);
    upper = max([scratchValues; fusionValues]);
    padding = max((upper - lower) * 0.08, 0.01);
    limits = [lower - padding, upper + padding];
    hold(ax, 'on');
    diagonal = plot(ax, limits, limits, '--', 'Color', [0.53 0.53 0.53], ...
        'LineWidth', 1.2, 'DisplayName', 'No change');
    worsePoints = scatter(ax, scratchValues(~improved), fusionValues(~improved), ...
        42, [0.96 0.62 0.04], 'filled', 'MarkerFaceAlpha', 0.82, ...
        'DisplayName', 'Worse / equal');
    improvedPoints = scatter(ax, scratchValues(improved), fusionValues(improved), ...
        42, colors(3, :), 'filled', 'MarkerFaceAlpha', 0.82, ...
        'DisplayName', 'Improved');
    hold(ax, 'off');
    xlim(ax, limits);
    ylim(ax, limits);
    axis(ax, 'square');
    xlabel(ax, 'Scratch error (dB)');
    ylabel(ax, 'Fusion error (dB)');
    statisticRow = statistics( ...
        statistics.comparison == "fusion_vs_scratch" & ...
        statistics.metric == statisticMetrics(metricIndex), :);
    assert(height(statisticRow) == 1);
    title(ax, sprintf('%s\n%d/44 improved, paired p=%.2g', ...
        metricTitles(metricIndex), sum(improved), statisticRow.paired_t_p), ...
        'FontWeight', 'bold');
    ax.FontSize = 11;
    ax.TickDir = 'out';
    ax.GridAlpha = 0.18;
    grid(ax, 'on');
    if metricIndex == 1
        legend(ax, [improvedPoints, worsePoints, diagonal], ...
            'Location', 'southeast', 'Box', 'off');
    end
end
exportgraphics(pairedFigure, fullfile(figureRoot, ...
    'scratch_vs_fusion_paired_subjects.png'), 'Resolution', 180);
close(pairedFigure);

fprintf('Figures written to %s\n', figureRoot);
end
