function plot_v1_v2_v3_v31_reconstruction_comparison(v31Root)
%PLOT_V1_V2_V3_V31_RECONSTRUCTION_COMPARISON Compare strict test metrics.

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
if nargin < 1 || strlength(string(v31Root)) == 0
    v31Root = fullfile(projectRoot, 'artifacts', 'reconstruction', ...
        'mlp_cnn_n03_v31_finetune_v3');
end

v1Root = fullfile(projectRoot, 'results', 'residual_mlp', ...
    'mlp_n03_v1', 'evaluation');
v2Root = fullfile(projectRoot, 'results', 'residual_mlp', ...
    'mlp_n03_v2', 'evaluation');
v3Root = fullfile(projectRoot, 'results', 'residual_mlp_cnn', ...
    'mlp_cnn_n03_v3', 'evaluation');

v1 = readtable(fullfile(v1Root, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
v2 = readtable(fullfile(v2Root, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
v3 = readtable(fullfile(v3Root, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
v31 = readtable(fullfile(v31Root, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
assert(isequal(v1.Metric, v2.Metric) && isequal(v2.Metric, v3.Metric) ...
    && isequal(v3.Metric, v31.Metric), ...
    'v1, v2, v3, and v3.1 aggregate metric rows do not match.');
assert(max(abs(v1.MCAMean_dB - v31.MCAMean_dB)) < 1e-10, ...
    'The MCA baselines differ between reconstruction runs.');

metricLabels = [ ...
    "Full-sphere ERB"; ...
    "Contralateral 25 deg ERB"; ...
    "Contralateral >10 kHz"; ...
    "ILD MAE"];
absoluteValues = [ ...
    v31.MCAMean_dB, ...
    v1.CorrectedMean_dB, ...
    v2.CorrectedMean_dB, ...
    v3.CorrectedMean_dB, ...
    v31.CorrectedMean_dB];
relativeValues = [ ...
    v1.RelativeImprovement_percent, ...
    v2.RelativeImprovement_percent, ...
    v3.RelativeImprovement_percent, ...
    v31.RelativeImprovement_percent];

figuresRoot = fullfile(v31Root, 'figures');
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100, 100, 1750, 900]);
layout = tiledlayout(figureHandle, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

nexttile(layout);
bar(absoluteValues);
grid on;
ylabel('Mean test error (dB)');
title('Strict reconstruction metrics');
xticks(1:numel(metricLabels));
xticklabels(metricLabels);
xtickangle(20);
legend({'MCA', 'v1 MLP', 'v2 auditory MLP', ...
    'v3 MLP-CNN', 'v3.1 strict-ILD'}, 'Location', 'best');

nexttile(layout);
bar(relativeValues);
grid on;
ylabel('Improvement over MCA (%)');
title('Relative improvement on 12 unseen subjects');
xticks(1:numel(metricLabels));
xticklabels(metricLabels);
xtickangle(20);
legend({'v1 MLP', 'v2 auditory MLP', ...
    'v3 MLP-CNN', 'v3.1 strict-ILD'}, 'Location', 'best');

title(layout, 'Residual learning v1 / v2 / v3 / v3.1 strict comparison', ...
    'FontWeight', 'bold');
aggregateOutput = fullfile( ...
    figuresRoot, 'v1_v2_v3_v31_aggregate_comparison.png');
exportgraphics(figureHandle, aggregateOutput, 'Resolution', 180);
close(figureHandle);

v2Subjects = readtable(fullfile(v2Root, 'per_subject_metrics.csv'));
v3Subjects = readtable(fullfile(v3Root, 'per_subject_metrics.csv'));
v31Subjects = readtable(fullfile(v31Root, 'per_subject_metrics.csv'));
assert(isequal(v2Subjects.SubjectID, v3Subjects.SubjectID) ...
    && isequal(v3Subjects.SubjectID, v31Subjects.SubjectID), ...
    'v2, v3, and v3.1 subject rows do not match.');

ildValues = [ ...
    v2Subjects.CorrectedILDMAE_dB, ...
    v3Subjects.CorrectedILDMAE_dB, ...
    v31Subjects.CorrectedILDMAE_dB];
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100, 100, 1600, 850]);
bar(categorical("pp" + string(v31Subjects.SubjectID)), ildValues);
grid on;
ylabel('Strict HRIR ILD MAE (dB)');
xlabel('Unseen test subject');
title(sprintf(['Per-subject strict ILD: v3.1 improves %d/12 over v3 ' ...
    'and %d/12 over v2'], ...
    sum(ildValues(:, 3) < ildValues(:, 2)), ...
    sum(ildValues(:, 3) < ildValues(:, 1))));
legend({'v2 auditory MLP', 'v3 MLP-CNN', 'v3.1 strict-ILD'}, ...
    'Location', 'northwest');
ildOutput = fullfile(figuresRoot, 'v2_v3_v31_ild_per_subject.png');
exportgraphics(figureHandle, ildOutput, 'Resolution', 180);
close(figureHandle);

fprintf('Wrote %s\n', aggregateOutput);
fprintf('Wrote %s\n', ildOutput);
end
