function outputPaths = plot_film_siren_ranf_fsp_v351_validation_subject_hrtf( ...
        outputName, filmPredictionName, ranfPredictionName, ...
        fspPredictionName, mcarPredictionName)
%PLOT_FILM_SIREN_RANF_FSP_V351_VALIDATION_SUBJECT_HRTF Compare validation HRTFs.
%
% For each of the 44 locked SONICOM validation subjects, plot the left-ear
% HRTF at the pure-interpolation direction nearest (270 deg, 0 deg).  The
% reference is the evaluation anchor; the four reconstructions are the
% frozen FiLM-SIREN ensemble, RANF, FSP-AE, and MCAR v3.5.1.

if nargin < 1 || isempty(outputName)
    outputName = ...
        'sonicom_validation_film_siren_ranf_fsp_v351_subject_hrtf';
end
if nargin < 2 || isempty(filmPredictionName)
    filmPredictionName = [ ...
        'sonicom_film_siren_gl_final_cosine_c0_e140_' ...
        'ensemble_validation'];
end
if nargin < 3 || isempty(ranfPredictionName)
    ranfPredictionName = 'sonicom_ranf_q26_validation_frozen';
end
if nargin < 4 || isempty(fspPredictionName)
    fspPredictionName = 'sonicom_fsp_ae_q26_formal_validation';
end
if nargin < 5 || isempty(mcarPredictionName)
    mcarPredictionName = 'sonicom_q26_validation_v351_previous30_b70';
end
validateattributes(outputName, {'char', 'string'}, {'scalartext'});
validateattributes(filmPredictionName, {'char', 'string'}, {'scalartext'});
validateattributes(ranfPredictionName, {'char', 'string'}, {'scalartext'});
validateattributes(fspPredictionName, {'char', 'string'}, {'scalartext'});
validateattributes(mcarPredictionName, {'char', 'string'}, {'scalartext'});
outputName = char(outputName);
filmPredictionName = char(filmPredictionName);
ranfPredictionName = char(ranfPredictionName);
fspPredictionName = char(fspPredictionName);
mcarPredictionName = char(mcarPredictionName);

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
datasetRoot = fullfile(projectRoot, 'data', 'processed', ...
    'sonicom_residual_q26_v1');
splitFile = fullfile(projectRoot, 'configs', 'data', ...
    'sonicom_subject_split_v1.csv');
filmRoot = fullfile(projectRoot, 'artifacts', 'reconstruction', ...
    filmPredictionName);
ranfRoot = fullfile(projectRoot, 'artifacts', 'reconstruction', ...
    ranfPredictionName);
fspRoot = fullfile(projectRoot, 'artifacts', 'reconstruction', ...
    fspPredictionName);
mcarRoot = fullfile(projectRoot, 'artifacts', 'reconstruction', ...
    mcarPredictionName);
resultRoot = fullfile(projectRoot, 'results', outputName);
figuresRoot = fullfile(resultRoot, 'figures');
sofaToolboxRoot = fullfile(projectRoot, 'external', 'SUpDEq', ...
    'thirdParty', 'SOFAtoolbox-2.1.5', 'SOFAtoolbox');

assert(isfolder(datasetRoot), 'Dataset root not found: %s', datasetRoot);
assert(isfile(splitFile), 'Split file not found: %s', splitFile);
assert(isfolder(filmRoot), ...
    'FiLM-SIREN prediction root not found: %s', filmRoot);
assert(isfolder(ranfRoot), 'RANF prediction root not found: %s', ranfRoot);
assert(isfolder(fspRoot), 'FSP-AE prediction root not found: %s', fspRoot);
assert(isfolder(mcarRoot), 'MCAR prediction root not found: %s', mcarRoot);
assert(isfolder(sofaToolboxRoot), ...
    'SOFA toolbox root not found: %s', sofaToolboxRoot);
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end
addpath(sofaToolboxRoot);
SOFAstart;

splitTable = readtable(splitFile, 'TextType', 'string');
splitRows = splitTable(splitTable.split == "val", :);
assert(height(splitRows) == 44, ...
    'Expected exactly 44 locked validation subjects.');
assert(numel(unique(splitRows.subject_id)) == 44, ...
    'Validation subject identifiers must be unique.');

samplingRateHz = 44100;
nfft = 1024;
frequencyHzAll = (0:(nfft / 2)).' * samplingRateHz / nfft;
subjectCount = height(splitRows);
overview = repmat(struct( ...
    'subjectLabel', "", 'frequencyHz', [], 'referenceDb', [], ...
    'filmDb', [], 'ranfDb', [], 'fspDb', [], 'mcarDb', [], ...
    'azimuthDeg', NaN, 'elevationDeg', NaN), subjectCount, 1);

subjectLabelOut = strings(subjectCount, 1);
subjectIdOut = zeros(subjectCount, 1);
azimuthOut = zeros(subjectCount, 1);
elevationOut = zeros(subjectCount, 1);
filmMaeOut = zeros(subjectCount, 1);
mcarMaeOut = zeros(subjectCount, 1);
ranfMaeOut = zeros(subjectCount, 1);
fspMaeOut = zeros(subjectCount, 1);

for subjectIndex = 1:subjectCount
    subjectLabel = splitRows.subject_id(subjectIndex);
    sourceFile = fullfile(datasetRoot, 'subjects', char(subjectLabel), ...
        'q26.h5');
    filmFile = fullfile(filmRoot, 'subjects', char(subjectLabel), ...
        'prediction.h5');
    ranfFile = fullfile(ranfRoot, 'subjects', char(subjectLabel), ...
        'prediction.sofa');
    fspFile = fullfile(fspRoot, 'subjects', char(subjectLabel), ...
        'prediction.h5');
    mcarFile = fullfile(mcarRoot, 'subjects', char(subjectLabel), ...
        'prediction.h5');
    assert(isfile(sourceFile), 'Missing source HDF5: %s', sourceFile);
    assert(isfile(filmFile), 'Missing FiLM-SIREN prediction: %s', filmFile);
    assert(isfile(ranfFile), 'Missing RANF prediction: %s', ranfFile);
    assert(isfile(fspFile), 'Missing FSP-AE prediction: %s', fspFile);
    assert(isfile(mcarFile), 'Missing MCAR prediction: %s', mcarFile);
    assert(string(h5readatt(sourceFile, '/', 'split')) == "val", ...
        'Source split mismatch for %s.', subjectLabel);
    assert(string(h5readatt(filmFile, '/', 'split')) == "val", ...
        'FiLM-SIREN split mismatch for %s.', subjectLabel);
    assert(string(h5readatt(fspFile, '/', 'split')) == "val", ...
        'FSP-AE split mismatch for %s.', subjectLabel);
    assert(string(h5readatt(mcarFile, '/', 'split')) == "val", ...
        'MCAR split mismatch for %s.', subjectLabel);

    referenceDb = double(h5read(sourceFile, '/reference_logmag_db'));
    mcaDb = double(h5read(sourceFile, '/mca_logmag_db'));
    filmResidualDb = double(h5read(filmFile, ...
        '/predicted_residual_db'));
    mcarResidualDb = double(h5read(mcarFile, ...
        '/predicted_residual_db'));
    directionFeatures = double(h5read(sourceFile, '/direction_features'));
    interpolationMask = logical(h5read(sourceFile, ...
        '/interpolation_evaluation_mask'));
    interpolationMask = interpolationMask(:);
    selectedIndices = double(h5read(sourceFile, ...
        '/strict_ild/selected_bin_indices_zero_based')) + 1;
    selectedIndices = selectedIndices(:);

    fspRaw = double(h5read(fspFile, '/predicted_magnitude_db'));
    fspMagnitudeDb = permute(fspRaw, [1, 3, 2]);
    fspSelectedDb = fspMagnitudeDb(selectedIndices - 1, :, :);

    ranfSofa = SOFAload(ranfFile);
    ranfHrir = double(ranfSofa.Data.IR);
    assert(isequal(size(ranfHrir), [793, 2, 256]), ...
        'Unexpected RANF HRIR shape for %s.', subjectLabel);
    ranfPosition = double(ranfSofa.SourcePosition);
    azimuthDeg = directionFeatures(1, :).';
    elevationDeg = directionFeatures(2, :).';
    azimuthError = abs(mod(ranfPosition(:, 1) - azimuthDeg + 180, ...
        360) - 180);
    elevationError = abs(ranfPosition(:, 2) - elevationDeg);
    assert(max(azimuthError) < 1e-8 && max(elevationError) < 1e-8, ...
        'RANF SOFA direction order mismatch for %s.', subjectLabel);

    directionDistance = great_circle_distance( ...
        azimuthDeg, elevationDeg, 270, 0);
    directionDistance(~interpolationMask) = inf;
    [~, overviewIndex] = min(directionDistance);
    assert(interpolationMask(overviewIndex), ...
        'Selected direction is not interpolation-only for %s.', ...
        subjectLabel);

    ranfSpectrum = fft(squeeze(ranfHrir(overviewIndex, 1, :)), nfft);
    ranfSelectedDb = 20 * log10(max(abs( ...
        ranfSpectrum(selectedIndices)), 1e-10));
    frequencyHz = frequencyHzAll(selectedIndices);
    plotMask = frequencyHz >= 100 & frequencyHz <= 20000;

    assert(isequal(size(referenceDb), [numel(selectedIndices), 793, 2]), ...
        'Unexpected reference shape for %s.', subjectLabel);
    assert(isequal(size(mcaDb), size(referenceDb)) && ...
        isequal(size(filmResidualDb), size(referenceDb)) && ...
        isequal(size(mcarResidualDb), size(referenceDb)) && ...
        isequal(size(fspSelectedDb), size(referenceDb)), ...
        'Prediction tensor shape mismatch for %s.', subjectLabel);
    assert(all(isfinite(referenceDb), 'all') && ...
        all(isfinite(mcaDb), 'all') && ...
        all(isfinite(filmResidualDb), 'all') && ...
        all(isfinite(mcarResidualDb), 'all') && ...
        all(isfinite(fspSelectedDb), 'all') && ...
        all(isfinite(ranfSelectedDb), 'all'), ...
        'Non-finite HRTF magnitude for %s.', subjectLabel);

    referenceCurve = referenceDb(plotMask, overviewIndex, 1);
    mcaCurve = mcaDb(plotMask, overviewIndex, 1);
    filmCurve = mcaCurve + ...
        filmResidualDb(plotMask, overviewIndex, 1);
    mcarCurve = mcaCurve + ...
        mcarResidualDb(plotMask, overviewIndex, 1);
    fspCurve = fspSelectedDb(plotMask, overviewIndex, 1);
    ranfCurve = ranfSelectedDb(plotMask);

    overview(subjectIndex).subjectLabel = subjectLabel;
    overview(subjectIndex).frequencyHz = frequencyHz(plotMask);
    overview(subjectIndex).referenceDb = referenceCurve;
    overview(subjectIndex).filmDb = filmCurve;
    overview(subjectIndex).ranfDb = ranfCurve;
    overview(subjectIndex).fspDb = fspCurve;
    overview(subjectIndex).mcarDb = mcarCurve;
    overview(subjectIndex).azimuthDeg = azimuthDeg(overviewIndex);
    overview(subjectIndex).elevationDeg = elevationDeg(overviewIndex);

    subjectLabelOut(subjectIndex) = subjectLabel;
    subjectIdOut(subjectIndex) = double(extractAfter(subjectLabel, 1));
    azimuthOut(subjectIndex) = azimuthDeg(overviewIndex);
    elevationOut(subjectIndex) = elevationDeg(overviewIndex);
    filmMaeOut(subjectIndex) = mean(abs(filmCurve - referenceCurve));
    mcarMaeOut(subjectIndex) = mean(abs(mcarCurve - referenceCurve));
    ranfMaeOut(subjectIndex) = mean(abs(ranfCurve - referenceCurve));
    fspMaeOut(subjectIndex) = mean(abs(fspCurve - referenceCurve));
    fprintf('Validation HRTF comparison [%d/%d]: %s\n', ...
        subjectIndex, subjectCount, subjectLabel);
end

perSubject = table(subjectLabelOut, subjectIdOut, azimuthOut, ...
    elevationOut, filmMaeOut, mcarMaeOut, ranfMaeOut, fspMaeOut, ...
    'VariableNames', {'SubjectLabel', 'SubjectID', 'Azimuth_deg', ...
    'Elevation_deg', 'FiLMSIREN_SelectedDirectionMAE_dB', ...
    'MCARv351_SelectedDirectionMAE_dB', ...
    'RANF_SelectedDirectionMAE_dB', ...
    'FSPAE_SelectedDirectionMAE_dB'});
assert(height(perSubject) == 44 && ...
    numel(unique(perSubject.SubjectLabel)) == 44, ...
    'Per-subject output must contain 44 unique validation subjects.');
assert(all(isfinite(perSubject{:, vartype('numeric')}), 'all'), ...
    'Per-subject selected-direction metrics contain non-finite values.');
writetable(perSubject, fullfile(resultRoot, ...
    'selected_direction_per_subject.csv'));

method = ["FiLM-SIREN"; "MCAR v3.5.1"; "RANF"; "FSP-AE"];
methodValues = {filmMaeOut; mcarMaeOut; ranfMaeOut; fspMaeOut};
meanMae = cellfun(@mean, methodValues);
standardDeviationMae = cellfun(@std, methodValues);
medianMae = cellfun(@median, methodValues);
aggregate = table(method, meanMae, standardDeviationMae, medianMae, ...
    'VariableNames', {'Method', 'MeanMAE_dB', 'SubjectSD_dB', ...
    'MedianMAE_dB'});
aggregate = sortrows(aggregate, 'MeanMAE_dB', 'ascend');
aggregate.Rank = (1:height(aggregate)).';
writetable(aggregate, fullfile(resultRoot, ...
    'aggregate_selected_direction_mae.csv'));

figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [30, 30, 2200, 1900]);
layout = tiledlayout(figureHandle, 8, 6, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
colors = struct( ...
    'reference', [0.12, 0.12, 0.12], ...
    'film', [0.84, 0.15, 0.16], ...
    'mcar', [0.49, 0.18, 0.56], ...
    'ranf', [0.00, 0.45, 0.74], ...
    'fsp', [0.10, 0.58, 0.32]);
for subjectIndex = 1:subjectCount
    axisHandle = nexttile(layout);
    referenceLine = semilogx(axisHandle, ...
        overview(subjectIndex).frequencyHz, ...
        overview(subjectIndex).referenceDb, ...
        'Color', colors.reference, 'LineWidth', 0.9, ...
        'DisplayName', '参考真值');
    hold(axisHandle, 'on');
    filmLine = semilogx(axisHandle, ...
        overview(subjectIndex).frequencyHz, ...
        overview(subjectIndex).filmDb, ...
        'Color', colors.film, 'LineWidth', 1.55, ...
        'DisplayName', 'FiLM-SIREN');
    mcarLine = semilogx(axisHandle, ...
        overview(subjectIndex).frequencyHz, ...
        overview(subjectIndex).mcarDb, ...
        'Color', colors.mcar, 'LineWidth', 1.25, ...
        'DisplayName', 'MCAR v3.5.1');
    ranfLine = semilogx(axisHandle, ...
        overview(subjectIndex).frequencyHz, ...
        overview(subjectIndex).ranfDb, ...
        'Color', colors.ranf, 'LineWidth', 1.05, ...
        'DisplayName', 'RANF');
    fspLine = semilogx(axisHandle, ...
        overview(subjectIndex).frequencyHz, ...
        overview(subjectIndex).fspDb, ...
        'Color', colors.fsp, 'LineWidth', 1.05, ...
        'DisplayName', 'FSP-AE');
    hold(axisHandle, 'off');
    grid(axisHandle, 'on');
    axisHandle.GridAlpha = 0.18;
    axisHandle.MinorGridAlpha = 0.08;
    axisHandle.FontSize = 6.5;
    axisHandle.FontName = 'Arial';
    axisHandle.TickDir = 'out';
    xlim(axisHandle, [100, 20000]);
    ylim(axisHandle, [-60, 25]);
    title(axisHandle, sprintf('%s (%.0f°, %.0f°)', ...
        overview(subjectIndex).subjectLabel, ...
        overview(subjectIndex).azimuthDeg, ...
        overview(subjectIndex).elevationDeg), ...
        'FontSize', 7, 'Interpreter', 'none');
    if subjectIndex == 1
        legend(axisHandle, [referenceLine, filmLine, mcarLine, ...
            ranfLine, fspLine], 'Location', 'southwest', ...
            'FontSize', 5.5, 'Interpreter', 'none');
    end
end
title(layout, ['SONICOM 验证集逐被试左耳对侧 HRTF 重建：' ...
    'FiLM-SIREN 与三种基线（最近纯插值方向）'], ...
    'FontWeight', 'bold', 'FontName', 'Microsoft YaHei', ...
    'Interpreter', 'none');

pngPath = fullfile(figuresRoot, ...
    'validation44_subject_contralateral_hrtf_film_siren_comparison.png');
pdfPath = fullfile(figuresRoot, ...
    'validation44_subject_contralateral_hrtf_film_siren_comparison.pdf');
exportgraphics(figureHandle, pngPath, 'Resolution', 180);
exportgraphics(figureHandle, pdfPath, 'ContentType', 'vector');
close(figureHandle);

qualityCheck = table( ...
    ["Split"; "SubjectCount"; "ComparedMethodCount"; ...
    "CurveCountIncludingReference"; "SelectedDirectionRows"; ...
    "NonfiniteSelectedDirectionMetrics"; "TestSubjectsRead"], ...
    ["val"; string(subjectCount); "4"; "5"; ...
    string(height(perSubject)); ...
    string(sum(~isfinite(perSubject{:, vartype('numeric')}), 'all')); ...
    "0"], ...
    'VariableNames', {'Check', 'Value'});
writetable(qualityCheck, fullfile(resultRoot, 'quality_checks.csv'));

outputPaths = string({pngPath, pdfPath});
fprintf('Wrote validation subject HRTF comparison:\n%s\n%s\n', ...
    pngPath, pdfPath);
disp(aggregate);
end

function distanceDeg = great_circle_distance(azimuthDeg, elevationDeg, ...
        targetAzimuthDeg, targetElevationDeg)
azimuthRad = deg2rad(azimuthDeg);
elevationRad = deg2rad(elevationDeg);
targetAzimuthRad = deg2rad(targetAzimuthDeg);
targetElevationRad = deg2rad(targetElevationDeg);
cosineDistance = sin(elevationRad) * sin(targetElevationRad) + ...
    cos(elevationRad) .* cos(targetElevationRad) .* ...
    cos(azimuthRad - targetAzimuthRad);
distanceDeg = rad2deg(acos(max(-1, min(1, cosineDistance))));
end
