function evaluate_test_reconstruction(outputName, cacheName, ...
        outputRootOverride, cacheRootOverride, ...
        correctedMethod, correctedDisplayName)
%EVALUATE_TEST_RECONSTRUCTION Refill MCA magnitude and compute paper metrics.
%
% Predicted residuals are added in dB:
%   corrected_logmag = mca_logmag + predicted_residual
% The complex HRTF uses the original MCA phase at every corrected bin.

if nargin < 1 || isempty(outputName)
    outputName = 'mlp_n03_v1';
end
if nargin < 2 || isempty(cacheName)
    cacheName = outputName;
end
if nargin < 3
    outputRootOverride = '';
end
if nargin < 4
    cacheRootOverride = '';
end
if nargin < 5 || isempty(correctedMethod)
    correctedMethod = "MCA+ResidualMLP";
end
if nargin < 6 || isempty(correctedDisplayName)
    correctedDisplayName = "MCA + residual MLP";
end
validateattributes(outputName, {'char', 'string'}, {'scalartext'});
validateattributes(cacheName, {'char', 'string'}, {'scalartext'});
validateattributes(outputRootOverride, {'char', 'string'}, {'scalartext'});
validateattributes(cacheRootOverride, {'char', 'string'}, {'scalartext'});
validateattributes(correctedMethod, {'char', 'string'}, {'scalartext'});
validateattributes(correctedDisplayName, {'char', 'string'}, {'scalartext'});
outputName = char(outputName);
cacheName = char(cacheName);
outputRootOverride = char(outputRootOverride);
cacheRootOverride = char(cacheRootOverride);
correctedMethod = string(correctedMethod);
correctedDisplayName = string(correctedDisplayName);

scriptDir = fileparts(mfilename('fullpath'));
stageRoot = fileparts(scriptDir);
projectRoot = fileparts(stageRoot);
supdeqDir = fullfile(projectRoot, 'SUpDEq-master');
splitFile = fullfile(stageRoot, 'config', 'subject_split_v1.csv');
if isempty(outputRootOverride)
    outputRoot = fullfile(stageRoot, 'reconstruction', outputName);
else
    outputRoot = outputRootOverride;
end
subjectsRoot = fullfile(outputRoot, 'subjects');
if isempty(cacheRootOverride)
    cacheRoot = fullfile(stageRoot, 'reconstruction', cacheName);
else
    cacheRoot = cacheRootOverride;
end
cacheSubjectsRoot = fullfile(cacheRoot, 'subjects');
figuresRoot = fullfile(outputRoot, 'figures');
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end

originalDir = pwd;
restoreDirectory = onCleanup(@() cd(originalDir));
cd(supdeqDir);
supdeq_start;
cd(originalDir);

splitTable = readtable(splitFile, 'TextType', 'string');
testSubjects = splitTable.subject_id(splitTable.split == "test").';
assert(numel(testSubjects) == 12, 'Expected exactly 12 test subjects.');

configuration = struct( ...
    'subjectIds', testSubjects, ...
    'cacheName', cacheName, ...
    'cacheRoot', cacheRoot, ...
    'outputRoot', outputRoot, ...
    'correctedMethod', correctedMethod, ...
    'sparseOrder', 3, ...
    'residualDefinition', ...
        'reference_logmag_db - mca_logmag_db', ...
    'reconstructionDefinition', ...
        'MCA magnitude + predicted residual, original MCA phase', ...
    'erbFunction', 'AKerbError', ...
    'erbFrequencyRangeHz', [50, 22050], ...
    'regionRadiusDegrees', 25, ...
    'contralateralHighFrequencyMinimumHz', 10000, ...
    'contralateralDefinition', ...
        'Opposite open hemisphere, excluding median plane', ...
    'ildDefinition', ...
        '10*log10(left HRIR energy/right HRIR energy), horizontal 360 degrees', ...
    'matlabVersion', version, ...
    'startedAt', datetime('now', 'TimeZone', 'local'));

erbSummary = table();
highFrequencySummary = table();
ildSummary = table();
qualitySummary = table();
overviewSpectra = repmat(struct( ...
    'subjectId', [], 'frequencyHz', [], 'referenceDb', [], ...
    'mcaDb', [], 'correctedDb', []), numel(testSubjects), 1);

for subjectIndex = 1:numel(testSubjects)
    subjectId = testSubjects(subjectIndex);
    subjectDir = fullfile(subjectsRoot, sprintf('pp%d', subjectId));
    cacheSubjectDir = fullfile( ...
        cacheSubjectsRoot, sprintf('pp%d', subjectId));
    cacheFile = fullfile(cacheSubjectDir, 'complex_cache.mat');
    predictionFile = fullfile(subjectDir, 'predicted_residual.h5');
    assert(isfile(cacheFile), 'Missing complex cache: %s', cacheFile);
    assert(isfile(predictionFile), ...
        'Missing predicted residual: %s', predictionFile);

    loaded = load(cacheFile, 'cache');
    cache = loaded.cache;
    prediction = h5read(predictionFile, '/predicted_residual_db');
    expectedSize = [sum(cache.frequencyMask), ...
        size(cache.denseGrid, 1) + size(cache.horizontalGrid, 1), 2];
    assert(isequal(size(prediction), expectedSize), ...
        'Unexpected prediction size for pp%d: %s, expected %s.', ...
        subjectId, mat2str(size(prediction)), mat2str(expectedSize));

    predictedLeftDb = double(prediction(:, :, 1).');
    predictedRightDb = double(prediction(:, :, 2).');
    mcaLeft = double(cache.mcaLeft);
    mcaRight = double(cache.mcaRight);
    referenceLeft = double(cache.referenceLeft);
    referenceRight = double(cache.referenceRight);
    [correctedLeft, leftQuality] = refill_magnitude( ...
        mcaLeft, predictedLeftDb, cache.frequencyMask);
    [correctedRight, rightQuality] = refill_magnitude( ...
        mcaRight, predictedRightDb, cache.frequencyMask);

    [referenceHrirLeft, referenceHrirRight] = hrtf_to_hrir( ...
        referenceLeft, referenceRight, cache.fftOversize);
    [mcaHrirLeft, mcaHrirRight] = hrtf_to_hrir( ...
        mcaLeft, mcaRight, cache.fftOversize);
    [correctedHrirLeft, correctedHrirRight] = hrtf_to_hrir( ...
        correctedLeft, correctedRight, cache.fftOversize);

    denseCount = size(cache.denseGrid, 1);
    denseIndices = 1:denseCount;
    horizontalIndices = denseCount + (1:size(cache.horizontalGrid, 1));
    weights = cache.denseGrid(:, 3);
    weights = weights / sum(weights);
    frontMask = great_circle_mask(cache.denseGrid, [0, 90], ...
        configuration.regionRadiusDegrees);
    leftContra25Mask = great_circle_mask(cache.denseGrid, [270, 90], ...
        configuration.regionRadiusDegrees);
    rightContra25Mask = great_circle_mask(cache.denseGrid, [90, 90], ...
        configuration.regionRadiusDegrees);

    [mcaErbLeft, erbFrequencyHz] = AKerbError( ...
        mcaHrirLeft(:, denseIndices), ...
        referenceHrirLeft(:, denseIndices), ...
        [50 cache.samplingRateHz / 2], cache.samplingRateHz);
    mcaErbRight = AKerbError( ...
        mcaHrirRight(:, denseIndices), ...
        referenceHrirRight(:, denseIndices), ...
        [50 cache.samplingRateHz / 2], cache.samplingRateHz);
    correctedErbLeft = AKerbError( ...
        correctedHrirLeft(:, denseIndices), ...
        referenceHrirLeft(:, denseIndices), ...
        [50 cache.samplingRateHz / 2], cache.samplingRateHz);
    correctedErbRight = AKerbError( ...
        correctedHrirRight(:, denseIndices), ...
        referenceHrirRight(:, denseIndices), ...
        [50 cache.samplingRateHz / 2], cache.samplingRateHz);

    erbSummary = [erbSummary; ...
        make_erb_rows(subjectId, "MCA", "Left", abs(mcaErbLeft), ...
            weights, frontMask, leftContra25Mask); ...
        make_erb_rows(subjectId, "MCA", "Right", abs(mcaErbRight), ...
            weights, frontMask, rightContra25Mask); ...
        make_erb_rows(subjectId, correctedMethod, "Left", ...
            abs(correctedErbLeft), weights, frontMask, leftContra25Mask); ...
        make_erb_rows(subjectId, correctedMethod, "Right", ...
            abs(correctedErbRight), weights, frontMask, ...
            rightContra25Mask)]; %#ok<AGROW>

    highFrequencySummary = [highFrequencySummary; ...
        make_high_frequency_row(subjectId, "MCA", "Left", ...
            mcaLeft(denseIndices, :), ...
            referenceLeft(denseIndices, :), cache.frequencyHz, ...
            cache.denseGrid, weights); ...
        make_high_frequency_row(subjectId, "MCA", "Right", ...
            mcaRight(denseIndices, :), ...
            referenceRight(denseIndices, :), cache.frequencyHz, ...
            cache.denseGrid, weights); ...
        make_high_frequency_row(subjectId, correctedMethod, "Left", ...
            correctedLeft(denseIndices, :), ...
            referenceLeft(denseIndices, :), cache.frequencyHz, ...
            cache.denseGrid, weights); ...
        make_high_frequency_row(subjectId, correctedMethod, "Right", ...
            correctedRight(denseIndices, :), ...
            referenceRight(denseIndices, :), cache.frequencyHz, ...
            cache.denseGrid, weights)]; %#ok<AGROW>

    referenceIld = calculate_ild( ...
        referenceHrirLeft(:, horizontalIndices), ...
        referenceHrirRight(:, horizontalIndices));
    mcaIld = calculate_ild( ...
        mcaHrirLeft(:, horizontalIndices), ...
        mcaHrirRight(:, horizontalIndices));
    correctedIld = calculate_ild( ...
        correctedHrirLeft(:, horizontalIndices), ...
        correctedHrirRight(:, horizontalIndices));
    ildSummary = [ildSummary; ...
        make_ild_row(subjectId, "MCA", mcaIld, referenceIld); ...
        make_ild_row(subjectId, correctedMethod, ...
            correctedIld, referenceIld)]; %#ok<AGROW>

    qualitySummary = [qualitySummary; table( ...
        subjectId, leftQuality.maxPhaseErrorRad, ...
        rightQuality.maxPhaseErrorRad, ...
        leftQuality.maxMagnitudeIdentityErrorDb, ...
        rightQuality.maxMagnitudeIdentityErrorDb, ...
        min(predictedLeftDb, [], 'all'), ...
        max(predictedLeftDb, [], 'all'), ...
        min(predictedRightDb, [], 'all'), ...
        max(predictedRightDb, [], 'all'), ...
        'VariableNames', {'SubjectID', ...
        'LeftMaxPhaseError_rad', 'RightMaxPhaseError_rad', ...
        'LeftMaxMagnitudeIdentityError_dB', ...
        'RightMaxMagnitudeIdentityError_dB', ...
        'LeftPredictionMinimum_dB', 'LeftPredictionMaximum_dB', ...
        'RightPredictionMinimum_dB', ...
        'RightPredictionMaximum_dB'})]; %#ok<AGROW>

    plot_subject_comparison(subjectId, cache, ...
        referenceLeft, referenceRight, mcaLeft, mcaRight, ...
        correctedLeft, correctedRight, erbFrequencyHz, ...
        mcaErbLeft, mcaErbRight, correctedErbLeft, correctedErbRight, ...
        weights, referenceIld, mcaIld, correctedIld, figuresRoot, ...
        correctedDisplayName);

    leftContralateralIndex = denseCount + 271;
    plotMask = cache.frequencyHz >= 100 & cache.frequencyHz <= 20000;
    overviewSpectra(subjectIndex).subjectId = subjectId;
    overviewSpectra(subjectIndex).frequencyHz = cache.frequencyHz(plotMask);
    overviewSpectra(subjectIndex).referenceDb = magnitude_db( ...
        referenceLeft(leftContralateralIndex, plotMask));
    overviewSpectra(subjectIndex).mcaDb = magnitude_db( ...
        mcaLeft(leftContralateralIndex, plotMask));
    overviewSpectra(subjectIndex).correctedDb = magnitude_db( ...
        correctedLeft(leftContralateralIndex, plotMask));

    fprintf('Evaluated pp%d (%d/%d).\n', ...
        subjectId, subjectIndex, numel(testSubjects));
end

perSubject = make_per_subject_summary( ...
    testSubjects, erbSummary, highFrequencySummary, ildSummary, ...
    correctedMethod);
aggregate = make_aggregate_summary(perSubject);

writetable(erbSummary, fullfile(outputRoot, 'erb_summary.csv'));
writetable(highFrequencySummary, fullfile( ...
    outputRoot, 'contralateral_high_frequency_summary.csv'));
writetable(ildSummary, fullfile(outputRoot, 'ild_summary.csv'));
writetable(qualitySummary, fullfile(outputRoot, ...
    'reconstruction_quality.csv'));
writetable(perSubject, fullfile(outputRoot, ...
    'per_subject_metrics.csv'));
writetable(aggregate, fullfile(outputRoot, ...
    'aggregate_metrics.csv'));
plot_overview_spectra(overviewSpectra, figuresRoot, correctedDisplayName);
plot_metric_overview(perSubject, figuresRoot, correctedDisplayName);

configuration.finishedAt = datetime('now', 'TimeZone', 'local');
configuration.completedSubjectCount = numel(testSubjects);
save(fullfile(outputRoot, 'evaluation_results.mat'), ...
    'configuration', 'erbSummary', 'highFrequencySummary', ...
    'ildSummary', 'qualitySummary', 'perSubject', 'aggregate', '-v7.3');
fprintf('Evaluation complete. Results: %s\n', outputRoot);
disp(aggregate);
clear restoreDirectory;
end

function [corrected, quality] = refill_magnitude( ...
        mca, predictedResidualDb, frequencyMask)
magnitudeFloorDb = -200;
mcaSelected = mca(:, frequencyMask);
mcaMagnitudeDb = magnitude_db(mcaSelected);
correctedMagnitudeDb = mcaMagnitudeDb + predictedResidualDb;
corrected = mca;
corrected(:, frequencyMask) = 10 .^ ...
    (correctedMagnitudeDb / 20) .* exp(1i * angle(mcaSelected));
phaseError = angle(corrected(:, frequencyMask) .* conj(mcaSelected));
recoveredMagnitudeDb = magnitude_db(corrected(:, frequencyMask));
quality = struct( ...
    'maxPhaseErrorRad', max(abs(phaseError), [], 'all'), ...
    'maxMagnitudeIdentityErrorDb', max(abs( ...
        recoveredMagnitudeDb - correctedMagnitudeDb), [], 'all'), ...
    'magnitudeFloorDb', magnitudeFloorDb);
assert(quality.maxPhaseErrorRad <= 1e-5, ...
    'Corrected HRTF does not preserve MCA phase.');
assert(quality.maxMagnitudeIdentityErrorDb <= 1e-4, ...
    'Corrected HRTF magnitude does not match dB refill.');
end

function valuesDb = magnitude_db(values)
valuesDb = 20 * log10(max(abs(values), 1e-10));
end

function [leftHrir, rightHrir] = hrtf_to_hrir( ...
        leftHrtf, rightHrtf, fftOversize)
leftHrir = real(ifft(AKsingle2bothSidedSpectrum(leftHrtf.')));
rightHrir = real(ifft(AKsingle2bothSidedSpectrum(rightHrtf.')));
hrirLength = size(leftHrir, 1) / fftOversize;
leftHrir = leftHrir(1:hrirLength, :);
rightHrir = rightHrir(1:hrirLength, :);
end

function mask = great_circle_mask(grid, center, radiusDegrees)
dotProduct = sind(grid(:, 2)) .* sind(center(2)) .* ...
    cosd(grid(:, 1) - center(1)) + ...
    cosd(grid(:, 2)) .* cosd(center(2));
distanceDegrees = acosd(min(1, max(-1, dotProduct)));
mask = distanceDegrees <= radiusDegrees + 1e-10;
end

function rows = make_erb_rows(subjectId, method, ear, errorDb, ...
        weights, frontMask, contraMask)
regions = ["FullSphere", "Frontal25deg", "Contralateral25deg"];
masks = {true(size(weights)), frontMask, contraMask};
rows = table();
for regionIndex = 1:numel(regions)
    mask = masks{regionIndex};
    regionWeights = weights(mask);
    regionWeights = regionWeights / sum(regionWeights);
    meanByBand = errorDb(:, mask) * regionWeights;
    rows = [rows; table(subjectId, method, ear, ...
        regions(regionIndex), sum(mask), mean(meanByBand), ...
        'VariableNames', {'SubjectID', 'Method', 'Ear', 'Region', ...
        'DirectionCount', 'MeanERBError_dB'})]; %#ok<AGROW>
end
end

function row = make_high_frequency_row(subjectId, method, ear, ...
        estimate, reference, frequencyHz, grid, weights)
highMask = frequencyHz > 10000 & frequencyHz <= 22050;
y = sind(grid(:, 2)) .* sind(grid(:, 1));
if ear == "Left"
    directionMask = y < -1e-12;
else
    directionMask = y > 1e-12;
end
directionWeights = weights(directionMask);
directionWeights = directionWeights / sum(directionWeights);
errorDb = abs(magnitude_db(estimate(directionMask, highMask)) - ...
    magnitude_db(reference(directionMask, highMask)));
weightedByFrequency = directionWeights.' * errorDb;
row = table(subjectId, method, ear, sum(directionMask), sum(highMask), ...
    min(frequencyHz(highMask)), max(frequencyHz(highMask)), ...
    mean(weightedByFrequency), median(errorDb, 'all'), ...
    'VariableNames', {'SubjectID', 'Method', 'Ear', ...
    'DirectionCount', 'FrequencyBinCount', 'MinimumFrequency_Hz', ...
    'MaximumFrequency_Hz', 'WeightedMeanAbsoluteError_dB', ...
    'UnweightedMedianAbsoluteError_dB'});
end

function ild = calculate_ild(leftHrir, rightHrir)
leftEnergy = sum(abs(leftHrir) .^ 2, 1);
rightEnergy = sum(abs(rightHrir) .^ 2, 1);
ild = 10 * log10(leftEnergy ./ rightEnergy).';
end

function row = make_ild_row(subjectId, method, estimate, reference)
errorDb = estimate - reference;
row = table(subjectId, method, numel(errorDb), ...
    mean(abs(errorDb)), sqrt(mean(errorDb .^ 2)), max(abs(errorDb)), ...
    'VariableNames', {'SubjectID', 'Method', 'DirectionCount', ...
    'MeanAbsoluteILDError_dB', 'RMSEILDError_dB', ...
    'MaximumAbsoluteILDError_dB'});
end

function summary = make_per_subject_summary( ...
        subjectIds, erbRows, highFrequencyRows, ildRows, correctedMethod)
summary = table();
for subjectId = subjectIds
    mcaFull = mean(erbRows.MeanERBError_dB( ...
        erbRows.SubjectID == subjectId & erbRows.Method == "MCA" & ...
        erbRows.Region == "FullSphere"));
    correctedFull = mean(erbRows.MeanERBError_dB( ...
        erbRows.SubjectID == subjectId & ...
        erbRows.Method == correctedMethod & ...
        erbRows.Region == "FullSphere"));
    mcaContra25 = mean(erbRows.MeanERBError_dB( ...
        erbRows.SubjectID == subjectId & erbRows.Method == "MCA" & ...
        erbRows.Region == "Contralateral25deg"));
    correctedContra25 = mean(erbRows.MeanERBError_dB( ...
        erbRows.SubjectID == subjectId & ...
        erbRows.Method == correctedMethod & ...
        erbRows.Region == "Contralateral25deg"));
    mcaHigh = mean(highFrequencyRows.WeightedMeanAbsoluteError_dB( ...
        highFrequencyRows.SubjectID == subjectId & ...
        highFrequencyRows.Method == "MCA"));
    correctedHigh = mean( ...
        highFrequencyRows.WeightedMeanAbsoluteError_dB( ...
        highFrequencyRows.SubjectID == subjectId & ...
        highFrequencyRows.Method == correctedMethod));
    mcaIld = ildRows.MeanAbsoluteILDError_dB( ...
        ildRows.SubjectID == subjectId & ildRows.Method == "MCA");
    correctedIld = ildRows.MeanAbsoluteILDError_dB( ...
        ildRows.SubjectID == subjectId & ...
        ildRows.Method == correctedMethod);
    summary = [summary; table(subjectId, ...
        mcaFull, correctedFull, improvement_percent(mcaFull, correctedFull), ...
        mcaContra25, correctedContra25, ...
        improvement_percent(mcaContra25, correctedContra25), ...
        mcaHigh, correctedHigh, ...
        improvement_percent(mcaHigh, correctedHigh), ...
        mcaIld, correctedIld, improvement_percent(mcaIld, correctedIld), ...
        'VariableNames', {'SubjectID', ...
        'MCAFullSphereERB_dB', 'CorrectedFullSphereERB_dB', ...
        'FullSphereERBImprovement_percent', ...
        'MCAContralateral25ERB_dB', ...
        'CorrectedContralateral25ERB_dB', ...
        'Contralateral25ERBImprovement_percent', ...
        'MCAContralateralHighFrequency_dB', ...
        'CorrectedContralateralHighFrequency_dB', ...
        'ContralateralHighFrequencyImprovement_percent', ...
        'MCAILDMAE_dB', 'CorrectedILDMAE_dB', ...
        'ILDImprovement_percent'})]; %#ok<AGROW>
end
end

function percent = improvement_percent(baseline, corrected)
percent = 100 * (baseline - corrected) / baseline;
end

function aggregate = make_aggregate_summary(perSubject)
metricNames = [ ...
    "FullSphereERB"; "Contralateral25ERB"; ...
    "ContralateralHighFrequency"; "ILDMAE"];
baselineVariables = [ ...
    "MCAFullSphereERB_dB"; "MCAContralateral25ERB_dB"; ...
    "MCAContralateralHighFrequency_dB"; "MCAILDMAE_dB"];
correctedVariables = [ ...
    "CorrectedFullSphereERB_dB"; ...
    "CorrectedContralateral25ERB_dB"; ...
    "CorrectedContralateralHighFrequency_dB"; ...
    "CorrectedILDMAE_dB"];
aggregate = table();
for metricIndex = 1:numel(metricNames)
    baseline = perSubject.(baselineVariables(metricIndex));
    corrected = perSubject.(correctedVariables(metricIndex));
    aggregate = [aggregate; table(metricNames(metricIndex), ...
        numel(baseline), mean(baseline), std(baseline), ...
        mean(corrected), std(corrected), ...
        mean(baseline) - mean(corrected), ...
        improvement_percent(mean(baseline), mean(corrected)), ...
        sum(corrected < baseline), ...
        'VariableNames', {'Metric', 'SubjectCount', ...
        'MCAMean_dB', 'MCAStd_dB', 'CorrectedMean_dB', ...
        'CorrectedStd_dB', 'AbsoluteImprovement_dB', ...
        'RelativeImprovement_percent', 'ImprovedSubjectCount'})]; %#ok<AGROW>
end
end

function plot_subject_comparison(subjectId, cache, ...
        referenceLeft, referenceRight, mcaLeft, mcaRight, ...
        correctedLeft, correctedRight, erbFrequencyHz, ...
        mcaErbLeft, mcaErbRight, correctedErbLeft, correctedErbRight, ...
        weights, referenceIld, mcaIld, correctedIld, figuresRoot, ...
        correctedDisplayName)
denseCount = size(cache.denseGrid, 1);
leftContralateralIndex = denseCount + 271;
rightContralateralIndex = denseCount + 91;
frequencyMask = cache.frequencyHz >= 100 & cache.frequencyHz <= 20000;

figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100, 100, 1400, 900]);
layout = tiledlayout(figureHandle, 2, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

nexttile(layout);
plot_spectrum(cache.frequencyHz(frequencyMask), ...
    referenceLeft(leftContralateralIndex, frequencyMask), ...
    mcaLeft(leftContralateralIndex, frequencyMask), ...
    correctedLeft(leftContralateralIndex, frequencyMask), ...
    correctedDisplayName);
title(sprintf('Left ear contralateral HRTF (azimuth 270^\\circ)'));

nexttile(layout);
plot_spectrum(cache.frequencyHz(frequencyMask), ...
    referenceRight(rightContralateralIndex, frequencyMask), ...
    mcaRight(rightContralateralIndex, frequencyMask), ...
    correctedRight(rightContralateralIndex, frequencyMask), ...
    correctedDisplayName);
title(sprintf('Right ear contralateral HRTF (azimuth 90^\\circ)'));

nexttile(layout);
mcaErbCurve = 0.5 * (abs(mcaErbLeft) * weights + ...
    abs(mcaErbRight) * weights);
correctedErbCurve = 0.5 * (abs(correctedErbLeft) * weights + ...
    abs(correctedErbRight) * weights);
semilogx(erbFrequencyHz, mcaErbCurve, 'LineWidth', 1.6);
hold on;
semilogx(erbFrequencyHz, correctedErbCurve, 'LineWidth', 1.6);
grid on;
xlim([50, cache.samplingRateHz / 2]);
xlabel('ERB center frequency (Hz)');
ylabel('Mean absolute magnitude error (dB)');
title('Full-sphere ERB magnitude error');
legend(["MCA", correctedDisplayName], 'Location', 'best');

nexttile(layout);
plot(0:359, referenceIld, 'k', 'LineWidth', 1.4);
hold on;
plot(0:359, mcaIld, '--', 'LineWidth', 1.2);
plot(0:359, correctedIld, 'LineWidth', 1.4);
grid on;
xlim([0, 359]);
xlabel('Horizontal azimuth (degrees)');
ylabel('ILD (dB)');
title('Horizontal-plane ILD');
legend(["Reference", "MCA", correctedDisplayName], ...
    'Location', 'best');

title(layout, sprintf( ...
    'HUTUBS pp%d: residual magnitude refill with original MCA phase', ...
    subjectId), 'FontWeight', 'bold');
exportgraphics(figureHandle, fullfile(figuresRoot, sprintf( ...
    'pp%d_reconstruction_comparison.png', subjectId)), ...
    'Resolution', 170);
close(figureHandle);
end

function plot_spectrum(frequencyHz, reference, mca, corrected, ...
        correctedDisplayName)
semilogx(frequencyHz, magnitude_db(reference), ...
    'k', 'LineWidth', 1.5);
hold on;
semilogx(frequencyHz, magnitude_db(mca), ...
    '--', 'LineWidth', 1.2);
semilogx(frequencyHz, magnitude_db(corrected), ...
    'LineWidth', 1.5);
grid on;
xlim([100, 20000]);
xlabel('Frequency (Hz)');
ylabel('Magnitude (dB)');
legend(["Reference", "MCA", correctedDisplayName], ...
    'Location', 'best');
end

function plot_overview_spectra(spectra, figuresRoot, correctedDisplayName)
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [50, 50, 1800, 1300]);
layout = tiledlayout(figureHandle, 4, 3, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
for index = 1:numel(spectra)
    nexttile(layout);
    semilogx(spectra(index).frequencyHz, spectra(index).referenceDb, ...
        'k', 'LineWidth', 1.1);
    hold on;
    semilogx(spectra(index).frequencyHz, spectra(index).mcaDb, ...
        '--', 'LineWidth', 0.9);
    semilogx(spectra(index).frequencyHz, spectra(index).correctedDb, ...
        'LineWidth', 1.1);
    grid on;
    xlim([100, 20000]);
    title(sprintf('pp%d', spectra(index).subjectId));
    if index > 9
        xlabel('Frequency (Hz)');
    end
    ylabel('dB');
end
legend(layout.Children(end), ...
    ["Reference", "MCA", correctedDisplayName], ...
    'Location', 'best');
title(layout, ['Test subjects: left-ear contralateral HRTF at ', ...
    'azimuth 270^\circ'], 'FontWeight', 'bold');
exportgraphics(figureHandle, fullfile(figuresRoot, ...
    'test12_contralateral_hrtf_overview.png'), 'Resolution', 180);
close(figureHandle);
end

function plot_metric_overview(perSubject, figuresRoot, correctedDisplayName)
figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [80, 80, 1600, 1000]);
layout = tiledlayout(figureHandle, 3, 1, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
subjectLabels = compose('pp%d', perSubject.SubjectID);

nexttile(layout);
bar([perSubject.MCAFullSphereERB_dB, ...
    perSubject.CorrectedFullSphereERB_dB]);
ylabel('ERB error (dB)');
title('Full-sphere ERB magnitude error');
grid on;
legend(["MCA", correctedDisplayName], 'Location', 'best');

nexttile(layout);
bar([perSubject.MCAContralateralHighFrequency_dB, ...
    perSubject.CorrectedContralateralHighFrequency_dB]);
ylabel('Error (dB)');
title('Contralateral hemisphere magnitude error above 10 kHz');
grid on;

nexttile(layout);
bar([perSubject.MCAILDMAE_dB, perSubject.CorrectedILDMAE_dB]);
ylabel('ILD MAE (dB)');
title('Horizontal-plane ILD error');
grid on;
xticks(1:height(perSubject));
xticklabels(subjectLabels);
xtickangle(30);

title(layout, 'MCA versus residual-refilled HRTF on 12 unseen subjects', ...
    'FontWeight', 'bold');
exportgraphics(figureHandle, fullfile(figuresRoot, ...
    'test12_metric_overview.png'), 'Resolution', 180);
close(figureHandle);
end
