function plot_v1_v2_v3_reconstruction_comparison()
%PLOT_V1_V2_V3_RECONSTRUCTION_COMPARISON Compare strict test-set metrics.

scriptDir = fileparts(mfilename('fullpath'));
v3Root = fileparts(scriptDir);
stageRoot = fileparts(v3Root);
v1Root = fullfile(stageRoot, 'reconstruction', 'mlp_n03_v1');
v2Root = fullfile(stageRoot, 'reconstruction', 'mlp_n03_v2');
v3ResultRoot = fullfile( ...
    v3Root, 'reconstruction', 'mlp_cnn_n03_v3_cnn_only');

v1 = readtable(fullfile(v1Root, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
v2 = readtable(fullfile(v2Root, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
v3 = readtable(fullfile(v3ResultRoot, 'aggregate_metrics.csv'), ...
    'TextType', 'string');
assert(isequal(v1.Metric, v2.Metric) && isequal(v2.Metric, v3.Metric), ...
    'v1, v2, and v3 aggregate metric rows do not match.');
assert(max(abs(v1.MCAMean_dB - v3.MCAMean_dB)) < 1e-10, ...
    'The MCA baselines differ between reconstruction runs.');

metricLabels = [ ...
    "Full-sphere ERB"; ...
    "Contralateral 25 deg ERB"; ...
    "Contralateral >10 kHz"; ...
    "ILD MAE"];
absoluteValues = [ ...
    v3.MCAMean_dB, ...
    v1.CorrectedMean_dB, ...
    v2.CorrectedMean_dB, ...
    v3.CorrectedMean_dB];
relativeValues = [ ...
    v1.RelativeImprovement_percent, ...
    v2.RelativeImprovement_percent, ...
    v3.RelativeImprovement_percent];

figureHandle = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [100, 100, 1600, 900]);
layout = tiledlayout(figureHandle, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

nexttile(layout);
bar(absoluteValues);
grid on;
ylabel('Mean test error (dB)');
title('Strict reconstruction metrics');
xticks(1:numel(metricLabels));
xticklabels(metricLabels);
xtickangle(20);
legend({'MCA', 'v1 MLP', 'v2 auditory MLP', 'v3 MLP-CNN'}, ...
    'Location', 'best');

nexttile(layout);
bar(relativeValues);
grid on;
ylabel('Improvement over MCA (%)');
title('Relative improvement on 12 unseen subjects');
xticks(1:numel(metricLabels));
xticklabels(metricLabels);
xtickangle(20);
legend({'v1 MLP', 'v2 auditory MLP', 'v3 MLP-CNN'}, ...
    'Location', 'best');

title(layout, 'Residual learning v1 / v2 / v3 strict comparison', ...
    'FontWeight', 'bold');
figuresRoot = fullfile(v3ResultRoot, 'figures');
if ~isfolder(figuresRoot)
    mkdir(figuresRoot);
end
outputFile = fullfile( ...
    figuresRoot, 'v1_v2_v3_aggregate_comparison.png');
exportgraphics(figureHandle, outputFile, 'Resolution', 180);
close(figureHandle);
fprintf('Wrote %s\n', outputFile);
end
